### ISSUE TITLE
Evaluate possibility to rewrite testsuite in Go

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-regressions#814]
To improve checking speed even more, JS is still interpreted every time. 
And in Go you can embed radare2 itself - so it'll be crazy fast, no need to run it every time: https://medium.com/dtoebe/embed-other-binaries-in-golang-binary-3f613314884c

**Comment by radare** [comment]
Wat. We want to test a clean run for every test. Reusing a single instance will not have the same results and cannot be paralelized

**Comment by radare** [comment]
Also embedding executables can be also done in js. This code is dumping the file to disk before running it. And its not considering race conditions so its vulnerable code

**Comment by Maijin** [comment]
-> r2r.js

**Comment by XVilka** [comment]
Judging by the FreeBSD builds it's very slow still, I am reopening the issue @radare @Maijin

**Comment by radare** [comment]
C is also an option btw :pp

**Comment by XVilka** [comment]
Yes, C or C++ - doesn't really matter, they just should be 1) mainstream 2) native.

**Comment by XVilka** [comment]
Good tutorial for porting code from NodeJS to Go: https://scotch.io/tutorials/moving-from-nodejs-to-go

**Comment by XVilka** [comment]
Here are the sources of NodeJS testing framework https://github.com/radare/node-r2r

**Comment by radare** [comment]
im rewriting it in V. it depends on libc, so it should be as portable as C, and the code looks nice to read. there are some bugs i found in the compiler (filled issues and submmited fixes and waiiting for feedback).

actually we could be writing this in C using the r2 APIs, and that would make much more sense to me, or even rust. i dont see much advantage in picking Go for this task right now. and i understand the portability concerns of the JS suite.

**Comment by radare** [comment]
https://github.com/radareorg/radare2-regressions/tree/master/new/r2r-v
